# Generated by Django 5.1.1 on 2024-10-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='surname',
            field=models.CharField(default='defalt value', max_length=250),
        ),
    ]
