# Generated by Django 5.1.1 on 2024-10-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_persons_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='surname',
            new_name='email',
        ),
        migrations.AddField(
            model_name='persons',
            name='message',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
