# Generated by Django 5.1.1 on 2024-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_filemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
