# Generated by Django 5.1.1 on 2024-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_filemanager_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanager',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
