# Generated by Django 5.1.1 on 2024-10-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_filemanager_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='', max_length=500, verbose_name='Enter you think'),
        ),
    ]
