# Generated by Django 5.1.1 on 2024-10-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video', models.CharField(max_length=200, verbose_name='Title Video')),
                ('url', models.FileField(upload_to='media/', verbose_name='Video')),
            ],
        ),
    ]
